In [ ]:
4 8 15 16 23 42

In [ ]:
# Киллер правила
# 
# 100 человек, каждый одновременно чья-то жертва и чей-то убийца  
# у каждого человека в конверте имя 
#
#
#  Филипп -> Паша -> Лера -> Саша -> Филипп
#  Филипп -> Лера -> Саша -> Филипп

# Устные вопросы:
# Сколько всего раздач существует?    100*99*98*...*3*2*1 = 100! 
# P(Паша получил конверт с собой) = 1/100

# 0, 1, ... , 98, 99 -> 100!
# 0 | 1, 2, ..., 98, 99 -> 1* 99! 
# 99!/100! = 1/100

# P(Лера получила конверт с собой) = 1/100

# P(Лера и Паша суицидники) = 98!/100! = 1/99*1/100

# 0, 1, ... , 98, 99 -> 100!
# 0, 1 | 2, ..., 98, 99 -> 1* 1 * 98! 

# P(Лера <-> Паша) = 1/99*1/100

# X - количество суицидов, Y - мэтчинги
# E(X), E(Y) - ? 

In [1]:
import numpy as np

In [2]:
xx = [1, 2, 3]
yy = [3, 2, 1]

xx + yy

[1, 2, 3, 3, 2, 1]

In [3]:
x = np.array(xx)
y = np.array(yy)

x + y

array([4, 4, 4])

In [6]:
x[x > 1]

array([2, 3])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [89]:
x = np.arange(5)
np.random.shuffle(x)
x

array([1, 4, 2, 3, 0])

In [92]:
np.sum(x == np.arange(5))

2

In [100]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [101]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [102]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
murder = np.array([1,2,3,4])
alive =  np.array([1,1,0,1])

np.random.choice(murder)

3

In [109]:
murder[alive == 1]

array([1, 2, 4])

In [131]:
reward = np.array([1, 0, 0, 1, 8, 0, 2, 1, 1, 4])

np.max(reward), np.argmax(reward)

(8, 4)

In [136]:
np.ones(5, dtype="int")

array([1, 1, 1, 1, 1])

In [ ]:
# model = LinearRegression()
# model2 = LinearRegression()

# зажарить(картошка)  - функция
# картошка.зажарить() - метод

In [137]:
class Killer:
    
    # конструктор (вызывается 1 раз при создании нового объекта)
    # self - способ сослаться на самого себя
    
    def __init__(self, n):
        # атрибуты класса 
        self.n = n
        self.murder_target = np.arange(n)
        self.alive = np.ones(n, dtype="int")
        self.reward = np.zeros(n, dtype="int")
        
        # методы, которые должны запуститься при создании экземпляра класса
        self._create_game()
        
    def __repr__(self):  # описание экземпляра
        return f"Killer({self.n})"
    
    def __str__(self): # более длинное человеческое описание 
        return f"Игра в киллера на {self.n} человек"
    
    # своё собственное сложение
    def __add__(self, other):
        n = self.n + other.n
        game = Killer(n)
        return game
    
    def _create_game(self):
        np.random.shuffle(self.murder_target)
    
    def is_suicide(self, i):
        return self.murder_target[i] == i
                
    def is_matching(self, i):
        return game.murder_target[game.murder_target[i]] == i
    
    def count_suicide(self):
        return np.sum(self.murder_target == np.arange(self.n))
        
    def count_matching(self):
        # задание 
        pass
        
    def step(self):
        killer_index = np.random.choice(self.murder_target[self.alive == 1])
        killer_target = self.murder_target[killer_index]
        
        self.alive[killer_target] = 0
        self.reward[killer_index] += 1
        
        self.murder_target[killer_index] = self.murder_target[killer_target]
        self.murder_target[killer_target] = -1
        
        print(f"Ход делает игрок {killer_index}")
        print(self.murder_target)
        print(self.alive)
        print(self.reward)
        print(" ")
        pass
    
    def play_game(self):
        print(f"Стартоая позиция:")
        print(self.murder_target)
        print(self.alive)
        print(self.reward)
        print(" ")        
        
        while np.sum(self.alive) > 0:
            self.step()
            
        print("Игра завершилась")
        print(f"Победил игрок {np.argmax(self.reward)} со счётом {np.max(self.reward)}")
    
    

In [87]:
game = Killer(5)
game

Killer(5)

In [88]:
print(game)

Игра в киллера на 5 человек


In [66]:
game1 = Killer(3)
game2 = Killer(2)

game = game1 + game2 
game

Killer(5)

Так какие же $E(X)$ и $E(Y)$? 

In [94]:
game = Killer(5)
game.murder_target

array([0, 4, 1, 3, 2])

In [95]:
game.is_suicide(1)

False

In [96]:
game.is_matching(0)

True

In [97]:
game.count_suicide()

2

In [104]:
n_obs = 1000
EX = np.zeros(n_obs)

for i in range(n_obs):
    game = Killer(100)
    EX[i] = game.count_suicide()
    
np.mean(EX)

0.99

Один шаг игры. Случайная пара людей => убийство.

In [ ]:
# [2, 1, 3, 0]  murder_target
# [1, 1, 1, 1]  alive

# [2, -, 3, 0] 
# [1, 0, 1, 1]

# [2, -, -, 0] 
# [1, 0, 0, 1]

# [3, -, -, -] 
# [1, 0, 0, 0]

In [138]:
game = Killer(10)
game.murder_target

array([2, 9, 4, 6, 1, 8, 7, 3, 0, 5])

In [139]:
game.play_game()

Стартоая позиция:
[2 9 4 6 1 8 7 3 0 5]
[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
 
Ход делает игрок 3
[ 2  9  4  7  1  8 -1  3  0  5]
[1 1 1 1 1 1 0 1 1 1]
[0 0 0 1 0 0 0 0 0 0]
 
Ход делает игрок 5
[ 2  9  4  7  1  0 -1  3 -1  5]
[1 1 1 1 1 1 0 1 0 1]
[0 0 0 1 0 1 0 0 0 0]
 
Ход делает игрок 5
[-1  9  4  7  1  2 -1  3 -1  5]
[0 1 1 1 1 1 0 1 0 1]
[0 0 0 1 0 2 0 0 0 0]
 
Ход делает игрок 2
[-1  9  1  7 -1  2 -1  3 -1  5]
[0 1 1 1 0 1 0 1 0 1]
[0 0 1 1 0 2 0 0 0 0]
 
Ход делает игрок 2
[-1 -1  9  7 -1  2 -1  3 -1  5]
[0 0 1 1 0 1 0 1 0 1]
[0 0 2 1 0 2 0 0 0 0]
 
Ход делает игрок 2
[-1 -1  5  7 -1  2 -1  3 -1 -1]
[0 0 1 1 0 1 0 1 0 0]
[0 0 3 1 0 2 0 0 0 0]
 
Ход делает игрок 7
[-1 -1  5 -1 -1  2 -1  7 -1 -1]
[0 0 1 0 0 1 0 1 0 0]
[0 0 3 1 0 2 0 1 0 0]
 
Ход делает игрок 7
[-1 -1  5 -1 -1  2 -1 -1 -1 -1]
[0 0 1 0 0 1 0 0 0 0]
[0 0 3 1 0 2 0 2 0 0]
 
Ход делает игрок 2
[-1 -1  2 -1 -1 -1 -1 -1 -1 -1]
[0 0 1 0 0 0 0 0 0 0]
[0 0 4 1 0 2 0 2 0 0]
 
Ход делает игрок 2
[-1 -1 -1 -1 -1 -1 -1 

 __Ещё вопросы:__ 
 
 - Математическое ожидание числа цепочек в игре
 - Математическое ожидание максимально длинной цепочки 
 - Математическое ожидание очков у победителя 
 
 ------
 
 - Поменялись правила игры! Если возникает мэтчинг или суицид, мы случайно меняем конверты между двумя людьми при суициде и между 4 людьми при мэтчинге. Математическое ожидание числа таких обменов. 
 
 

In [ ]:
#[1, 0, 3, 4, 2]   # 2 цепи: 
                   # 1 -> 0 -> 1 
                   # 2 -> 3 -> 4 -> 2